version: '2'

networks:
  zetcd-test-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

volumes:
  mesos-master-1:
  mesos-master-2:
  mesos-master-3:

services:
  zk0:
    image: zookeeper:3.4.9
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=172.20.0.2:2888:3888
    networks:
      zetcd-test-net:
        ipv4_address: 172.20.0.2

  zetcd0:
    build: zetcd
    command: -zkbridge=172.20.0.2:2181 -zkaddr=:2181 -logtostderr -v 10
    networks:
      zetcd-test-net:
        ipv4_address: 172.20.0.12
    depends_on:
    - zk0
    
  mesos-master-1:
    image: mesosphere/mesos:1.2.0-rc2
    command: mesos-master --registry=replicated_log --work_dir=/data
    volumes:
    - mesos-master-1:/data
    environment:
      - MESOS_QUORUM=2
      - MESOS_PORT=5050
      - MESOS_ZK=zk://172.20.0.12:2181/mesos
      - MESOS_HOSTNAME=172.20.0.22
    restart: unless-stopped
    ports:
    - 5050:5050
    networks:
      zetcd-test-net:
        ipv4_address: 172.20.0.22
    depends_on:
    - zetcd0

  mesos-master-2:
    image: mesosphere/mesos:1.2.0-rc2
    command: mesos-master --registry=replicated_log --work_dir=/data
    volumes:
    - mesos-master-2:/data
    environment:
      - MESOS_QUORUM=2
      - MESOS_PORT=5051
      - MESOS_ZK=zk://172.20.0.12:2181/mesos
      - MESOS_HOSTNAME=172.20.0.23
    restart: unless-stopped
    ports:
    - 5051:5051
    networks:
      zetcd-test-net:
        ipv4_address: 172.20.0.23
    depends_on:
    - zetcd0

  mesos-master-3:
    image: mesosphere/mesos:1.2.0-rc2
    command: mesos-master --registry=replicated_log --work_dir=/data
    volumes:
    - mesos-master-3:/data
    environment:
      - MESOS_QUORUM=2
      - MESOS_PORT=5052
      - MESOS_ZK=zk://172.20.0.12:2181/mesos
      - MESOS_HOSTNAME=172.20.0.24
    restart: unless-stopped
    ports:
    - 5052:5052
    networks:
      zetcd-test-net:
        ipv4_address: 172.20.0.24
    depends_on:
    - zetcd0

  mesos-slave-1:
    image: mesosphere/mesos:1.2.0-rc2
    privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker:ro
    - /sys/fs/cgroup:/sys/fs/cgroup
    command: mesos-agent
                --no-systemd_enable_support
                --no-hostname_lookup
    environment:
      - MESOS_CONTAINERIZERS=docker
      - MESOS_WORK_DIR=/data
      - MESOS_MASTER=zk://172.20.0.12:2181/mesos
      - MESOS_DOCKER_STOP_TIMEOUT=2mins
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_PORT=5060
      - MESOS_HOSTNAME=172.20.0.30
    restart: unless-stopped
    ports:
    - 5060:5060    
    networks:
      zetcd-test-net:
        ipv4_address: 172.20.0.30
    depends_on:
    - zetcd0
    
  marathon:
    image: mesosphere/marathon
    command: --master zk://172.20.0.12:2181/mesos
             --zk zk://172.20.0.12:2181/marathon
    ports:
    - 8080:8080
    networks:
      zetcd-test-net:
        ipv4_address: 172.20.0.40
